# mysql
mysql:
  host: 192.168.150.101
  port: 3306
  database: my_blog_db
  username: root
  password: 123456

# redis
redis:
  host: 192.168.150.101
  port: 6379
  database: 0

# JWT
jwt:
  secret: myblog
  # 过期时间 1天 单位ms
  expire: 86400000


security:
  include-path:
    - /admin/**
  exclude-path:
    - /admin/user/login
    - /admin/user/captcha